### ISSUE TITLE
WebRTC.io demo fails with Chrome Version 25.0.1329.0 canary

### ISSUE THREAD

**Issue by ignjat** [webRTC-io/webrtc.io-demo#7]
Below is the specific error being reported. This is with all the changes needed to switch to RTCPeerConnection API (Chrome 23+) fixed.

  /**
- Connects to the websocket server.
  */
  rtc.connect = function(server, room) {
    room = room || ""; // by default, join a room called the blank string
    rtc._socket = new WebSocket(server);
  
    rtc._socket.onopen = function() {
  
  ```
  rtc._socket.send(JSON.stringify({
  ```
  
  Uncaught TypeError: Type error
      "eventName": "join_room",
      "data":{
        "room": room
      }
    }), function(error){
        if(error){console.log(error);}
      });

**Comment by benbrittain** [comment]
This should be fixed now. We were a little behind on updating the syntax.

**Comment by ignjat** [comment]
This still doesn't work for me in Canary, same error same piece of code. I'll double check...

**Comment by ignjat** [comment]
Definitely still broken. Current Canary build is 25.0.1337.0 and it throws the same error.

**Comment by warrenjmcdonald** [comment]
This is still an issue for me in Version 26.0.1408.1 canary

**Comment by jlindsay** [comment]
I just pulled from the git, I'm getting the same error.

**Comment by danielkutik** [comment]
this issue is in [webRTC](https://github.com/webRTC) / **[webrtc.io-client](https://github.com/webRTC/webrtc.io-client)**
